// Mock Pulse Data for Development
// Used when VITE_PULSE_API_URL is not configured

import type {
  RelationshipProfile,
  AIInsights,
  ContactInteraction,
  RecommendedAction,
} from '../types/pulseContacts';

// ============================================
// MOCK RELATIONSHIP PROFILES
// ============================================

export const MOCK_RELATIONSHIP_PROFILES: RelationshipProfile[] = [
  {
    id: 'profile-1',
    user_id: 'user-1',
    canonical_email: 'john.smith@example.com',
    display_name: 'John Smith',
    first_name: 'John',
    last_name: 'Smith',
    phone_number: '+1-555-0100',
    company: 'Acme Corp',
    title: 'VP of Engineering',
    linkedin_url: 'https://linkedin.com/in/johnsmith',
    timezone: 'America/New_York',
    avatar_url: 'https://i.pravatar.cc/150?img=12',
    relationship_score: 85,
    total_interactions: 247,
    last_interaction_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    communication_frequency: 'weekly',
    preferred_channel: 'email',
    tags: ['investor', 'technical', 'warm-lead'],
    notes: 'Met at Web Summit 2025. Interested in our API product.',
    is_favorite: true,
    is_blocked: false,
    created_at: '2025-06-01T12:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'profile-2',
    user_id: 'user-1',
    canonical_email: 'sarah.johnson@techstart.com',
    display_name: 'Sarah Johnson',
    first_name: 'Sarah',
    last_name: 'Johnson',
    phone_number: '+1-555-0200',
    company: 'TechStart Inc',
    title: 'CEO',
    linkedin_url: 'https://linkedin.com/in/sarahjohnson',
    timezone: 'America/Los_Angeles',
    avatar_url: 'https://i.pravatar.cc/150?img=5',
    relationship_score: 72,
    total_interactions: 156,
    last_interaction_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    communication_frequency: 'monthly',
    preferred_channel: 'meeting',
    tags: ['donor', 'board-member'],
    notes: 'Long-time supporter. Prefers in-person meetings.',
    is_favorite: true,
    is_blocked: false,
    created_at: '2024-03-15T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'profile-3',
    user_id: 'user-1',
    canonical_email: 'michael.chen@innovations.io',
    display_name: 'Michael Chen',
    first_name: 'Michael',
    last_name: 'Chen',
    phone_number: '+1-555-0300',
    company: 'Innovations.io',
    title: 'CTO',
    linkedin_url: 'https://linkedin.com/in/michaelchen',
    timezone: 'America/Chicago',
    avatar_url: 'https://i.pravatar.cc/150?img=33',
    relationship_score: 45,
    total_interactions: 89,
    last_interaction_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    communication_frequency: 'quarterly',
    preferred_channel: 'slack',
    tags: ['prospect', 'technical'],
    notes: 'Cold lead. Interested but low engagement.',
    is_favorite: false,
    is_blocked: false,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'profile-4',
    user_id: 'user-1',
    canonical_email: 'emily.rodriguez@foundation.org',
    display_name: 'Emily Rodriguez',
    first_name: 'Emily',
    last_name: 'Rodriguez',
    phone_number: '+1-555-0400',
    company: 'Community Foundation',
    title: 'Director of Grants',
    linkedin_url: 'https://linkedin.com/in/emilyrodriguez',
    timezone: 'America/Denver',
    avatar_url: 'https://i.pravatar.cc/150?img=47',
    relationship_score: 92,
    total_interactions: 412,
    last_interaction_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    communication_frequency: 'weekly',
    preferred_channel: 'email',
    tags: ['major-donor', 'foundation', 'active'],
    notes: 'Key relationship. Very engaged with our mission.',
    is_favorite: true,
    is_blocked: false,
    created_at: '2023-08-20T14:30:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'profile-5',
    user_id: 'user-1',
    canonical_email: 'david.kim@startup.ventures',
    display_name: 'David Kim',
    first_name: 'David',
    last_name: 'Kim',
    phone_number: '+1-555-0500',
    company: 'Startup Ventures',
    title: 'Partner',
    linkedin_url: 'https://linkedin.com/in/davidkim',
    timezone: 'America/Los_Angeles',
    avatar_url: 'https://i.pravatar.cc/150?img=68',
    relationship_score: 28,
    total_interactions: 12,
    last_interaction_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    communication_frequency: 'rare',
    preferred_channel: 'phone',
    tags: ['dormant', 'investor'],
    notes: 'Has not responded to recent outreach. May need re-engagement strategy.',
    is_favorite: false,
    is_blocked: false,
    created_at: '2024-10-05T11:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

// ============================================
// MOCK AI INSIGHTS
// ============================================

export const MOCK_AI_INSIGHTS: Record<string, AIInsights> = {
  'profile-1': {
    profile_id: 'profile-1',
    ai_communication_style: 'Professional and detail-oriented, prefers data-driven discussions with technical depth. Responds quickly to emails and appreciates concise summaries with actionable next steps.',
    ai_topics: ['API integration', 'enterprise pricing', 'security compliance', 'technical architecture', 'SLA requirements'],
    ai_sentiment_average: 0.72,
    ai_relationship_summary: 'Strong technical relationship. John is the key decision-maker for API tooling at Acme Corp. Has expressed strong interest in our enterprise plan and is currently in evaluation phase. Needs buy-in from his VP of Product for final approval. Responds well to technical demos, case studies, and detailed documentation.',
    ai_talking_points: [
      'Follow up on enterprise demo scheduled for next Tuesday - confirm attendees and agenda',
      'Share the fintech case study he requested (similar company size and use case)',
      'Discuss API rate limits, custom SLA options, and dedicated support channels',
      'Ask about their Q2 budget timeline and procurement process',
      'Offer technical deep-dive session with our engineering team',
    ],
    ai_next_actions: [
      {
        action: 'Send enterprise pricing proposal with custom SLA options',
        priority: 'high',
        due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        action: 'Schedule technical deep-dive with their engineering team',
        priority: 'medium',
        due_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        action: 'Send fintech case study and ROI calculator',
        priority: 'high',
        due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    confidence_score: 0.89,
    last_analyzed_at: new Date().toISOString(),
  },
  'profile-2': {
    profile_id: 'profile-2',
    ai_communication_style: 'Direct and mission-focused. Prefers in-person meetings and phone calls over email. Values personal relationships and long-term partnerships.',
    ai_topics: ['community impact', 'grant opportunities', 'program outcomes', 'partnership opportunities', 'board engagement'],
    ai_sentiment_average: 0.85,
    ai_relationship_summary: 'Outstanding relationship with Sarah Johnson at TechStart Inc. She has been a consistent supporter for over 2 years and recently joined our advisory board. Highly engaged with our mission and frequently advocates for us in her network. Last gift was $25,000 for the youth program.',
    ai_talking_points: [
      'Thank her for recent $25k donation and share impact metrics',
      'Invite to upcoming board retreat and annual gala',
      'Discuss potential corporate partnership with TechStart Inc',
      'Ask for introduction to other foundation leaders in her network',
      'Share Q4 program outcomes and success stories',
    ],
    ai_next_actions: [
      {
        action: 'Schedule lunch meeting to discuss corporate partnership',
        priority: 'medium',
        due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        action: 'Send personalized thank-you note with impact report',
        priority: 'high',
        due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    confidence_score: 0.92,
    last_analyzed_at: new Date().toISOString(),
  },
};

// ============================================
// MOCK INTERACTIONS
// ============================================

export const MOCK_INTERACTIONS: Record<string, ContactInteraction[]> = {
  'profile-1': [
    {
      id: 'interaction-1',
      profile_id: 'profile-1',
      interaction_type: 'email_sent',
      interaction_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      subject: 'Re: Enterprise API Pricing Discussion',
      snippet: 'Thanks for the detailed questions. Here\'s our enterprise pricing structure with the custom SLA options we discussed...',
      sentiment_score: 0.8,
      ai_topics: ['pricing', 'enterprise features', 'SLA'],
      ai_action_items: ['Schedule follow-up call', 'Send technical documentation'],
      ai_summary: 'Positive email discussing enterprise pricing options. Customer is interested but needs more details on custom SLAs and dedicated support channels. Good buying signals.',
      channel_metadata: {
        email_id: 'msg_abc123',
        thread_id: 'thread_xyz789',
        recipients: ['john@example.com'],
        cc: ['sarah@example.com'],
      },
      synced_at: new Date().toISOString(),
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'interaction-2',
      profile_id: 'profile-1',
      interaction_type: 'meeting',
      interaction_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      subject: 'Product Demo - Acme Corp',
      snippet: 'Conducted live demo of API platform. John asked excellent technical questions about authentication, rate limiting, and webhook reliability...',
      sentiment_score: 0.9,
      ai_topics: ['product demo', 'API integration', 'technical requirements', 'security'],
      ai_action_items: [
        'Send follow-up with answers to technical questions',
        'Schedule deeper technical dive with engineering team',
        'Provide access to sandbox environment',
      ],
      ai_summary: 'Very positive demo session. John was highly engaged and asked detailed technical questions about our API architecture. Strong buying signals and clear use case. Ready to move to enterprise pricing discussion.',
      channel_metadata: {
        meeting_id: 'mtg_def456',
        calendar_event_id: 'cal_ghi789',
        attendees: ['john@example.com', 'sarah@example.com', 'me@mycompany.com'],
      },
      duration_minutes: 45,
      synced_at: new Date().toISOString(),
      created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'interaction-3',
      profile_id: 'profile-1',
      interaction_type: 'slack_message',
      interaction_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      subject: 'Quick API question',
      snippet: 'Hey, quick question about your webhook retry logic...',
      sentiment_score: 0.5,
      ai_topics: ['technical support', 'webhooks'],
      ai_action_items: ['Provide documentation link'],
      ai_summary: 'Routine technical question about webhook implementation. Answered with documentation link.',
      channel_metadata: {
        slack_thread_id: 'thread_123',
        slack_channel: 'api-customers',
      },
      synced_at: new Date().toISOString(),
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  'profile-2': [
    {
      id: 'interaction-4',
      profile_id: 'profile-2',
      interaction_type: 'call',
      interaction_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      subject: 'Board Meeting Follow-up',
      snippet: 'Discussed Q4 fundraising goals and corporate partnership opportunities...',
      sentiment_score: 0.85,
      ai_topics: ['board engagement', 'fundraising', 'corporate partnership'],
      ai_action_items: ['Send board meeting summary', 'Draft corporate partnership proposal'],
      ai_summary: 'Excellent call with Sarah discussing strategic initiatives. She\'s enthusiastic about expanding corporate partnerships and offered to make introductions to other CEOs in her network.',
      channel_metadata: {
        call_duration: 35,
        call_type: 'outbound',
      },
      duration_minutes: 35,
      synced_at: new Date().toISOString(),
      created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// ============================================
// MOCK RECOMMENDED ACTIONS
// ============================================

export const MOCK_RECOMMENDED_ACTIONS: RecommendedAction[] = [
  {
    id: 'action-1',
    contact_id: 'profile-5',
    contact_name: 'David Kim',
    contact_score: 28,
    contact_trend: 'dormant',
    contact_company: 'Startup Ventures',
    priority: 'high',
    reason: 'Relationship at risk - No contact in 90 days',
    suggested_actions: [
      'Send personalized re-engagement email referencing last conversation',
      'Share recent news or achievement relevant to their interests',
      'Offer coffee meeting or quick call to catch up',
      'Ask if they\'d like to be removed from communications (give them an out)',
    ],
    due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    value_indicator: 'Previous donor - $5k lifetime',
    last_interaction_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    sentiment: -0.1,
    donor_stage: 'Lapsed Donor',
    lifetime_giving: 5000,
  },
  {
    id: 'action-2',
    contact_id: 'profile-3',
    contact_name: 'Michael Chen',
    contact_score: 45,
    contact_trend: 'falling',
    contact_company: 'Innovations.io',
    priority: 'medium',
    reason: 'Engagement declining - Move from warm to cold lead',
    suggested_actions: [
      'Send case study relevant to their industry',
      'Invite to upcoming webinar or event',
      'Offer free consultation or product demo',
      'Check in on their evaluation timeline',
    ],
    due_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    value_indicator: 'Prospect - High potential',
    last_interaction_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    sentiment: 0.2,
    donor_stage: 'Prospect',
    lifetime_giving: 0,
  },
  {
    id: 'action-3',
    contact_id: 'profile-1',
    contact_name: 'John Smith',
    contact_score: 85,
    contact_trend: 'rising',
    contact_company: 'Acme Corp',
    priority: 'opportunity',
    reason: 'Hot lead - Ready to close enterprise deal',
    suggested_actions: [
      'Send final pricing proposal with custom SLA',
      'Schedule contract review call with their legal team',
      'Offer pilot program or proof of concept',
      'Connect them with existing customer for reference',
    ],
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    value_indicator: 'Enterprise opportunity - $100k+ ARR',
    last_interaction_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sentiment: 0.8,
    donor_stage: 'Qualified Lead',
    lifetime_giving: 0,
  },
  {
    id: 'action-4',
    contact_id: 'profile-2',
    contact_name: 'Sarah Johnson',
    contact_score: 92,
    contact_trend: 'stable',
    contact_company: 'TechStart Inc',
    priority: 'high',
    reason: 'Major donor stewardship - Send thank you',
    suggested_actions: [
      'Send personalized thank-you note for recent $25k donation',
      'Share impact report showing how their gift made a difference',
      'Invite to exclusive donor event or site visit',
      'Ask for feedback on their giving experience',
    ],
    due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    value_indicator: 'Major Donor - $75k lifetime',
    last_interaction_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    sentiment: 0.9,
    donor_stage: 'Major Donor',
    lifetime_giving: 75000,
  },
];
